### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/orcid#6]
The app install but then the button to put my ID doesn't work 
I'm in latest NC12

**Comment by daita** [comment]
Have you put your API in the Admin Settings page ?

**Comment by Ricardosgeral** [comment]
How do I do that? It's not just Enable the app?

**Comment by daita** [comment]
Please check the installation instruction:

 _In the Admin Interface, fill the data with the API credential (Client ID + Client secret) from https://orcid.org/developer-tools. The redirect URL displayed in the Admin Interface (Nextcloud) will be used to setup your API on the ORCID Interface._

**Comment by Ricardosgeral** [comment]
Yep I was missing that step. It works now. Thanks
