### ISSUE TITLE
Admin Settings Section is not shown

### ISSUE THREAD

**Issue by drumdum** [nextcloud/orcid#8]
I'm running Nextcloud 14.0.4 and installed the orcid app version 1.0.0 from the app store. After that I can find the settings under personal settings but there is no orcid section anywhere in the admin settings. Therefore I cannot setup the authorization with orcid and I'm not able to use the app. Is there anything else I need to do other than activate the app?

**Comment by crohrandt** [comment]
I solved this issue. I had some problems with another app that prevented the whole additional admin settings from being shown.

**Comment by drumdum** [comment]
I solved this issue. Another app prevented the whole additional admin settings from being shown.
